from .logistic_regression import LogisticRegression
from .logistic_regression_penalized import LogisticRegressionPenalized
from .multinomial import SoftmaxClassifier
from .custom_cnn import CustomCNN
from .poor_cnn import PoorPerformingCNN